import argparse
import json
from datetime import datetime
from pathlib import Path

import joblib
import numpy as np
import torch

try:
    import lightgbm as lgb
except Exception as e:
    lgb = None
    _LGBM_IMPORT_ERROR = e

from build_paired_profile import normalize_name
from model_utils import load_dinov2_small, build_transform, extract_video_embeddings
from lgbm_utils import make_lgbm_features, mask_from_segments


def find_source_profile(profile, video_path):
    vk = normalize_name(Path(video_path).stem)
    best = None
    best_len = -1
    for sp in profile.get('source_profiles', []):
        rk = sp.get('raw_key') or normalize_name(sp.get('raw_stem', ''))
        if rk and (rk == vk or rk in vk or vk in rk):
            if len(rk) > best_len:
                best = sp
                best_len = len(rk)
    return best


def sample_training_rows(X, y, raw_name, max_neg_ratio, rng):
    pos_idx = np.flatnonzero(y == 1)
    neg_idx = np.flatnonzero(y == 0)
    if len(pos_idx) == 0:
        return None
    max_neg = min(len(neg_idx), int(max(1, len(pos_idx) * max_neg_ratio)))
    if max_neg < len(neg_idx):
        neg_idx = rng.choice(neg_idx, size=max_neg, replace=False)
    idx = np.concatenate([pos_idx, neg_idx])
    rng.shuffle(idx)
    return X[idx], y[idx], np.array([raw_name] * len(idx), dtype=object)


def main():
    ap = argparse.ArgumentParser(description='Train LightGBM KEEP-score model from paired raw↔edited profile segments.')
    ap.add_argument('--paired_profile', default='paired_profile.pkl')
    ap.add_argument('--out', default='lgbm_profile.pkl')
    ap.add_argument('--sample_fps', type=float, default=0.0, help='0 = use sample_fps saved in paired profile.')
    ap.add_argument('--input_size', type=int, default=0, help='0 = use input_size saved in paired profile.')
    ap.add_argument('--batch_size', type=int, default=64)
    ap.add_argument('--max_frames_per_video', type=int, default=0)
    ap.add_argument('--negative_ratio', type=float, default=4.0, help='Sample at most N negative frames per positive frame for each raw video.')
    ap.add_argument('--num_leaves', type=int, default=31)
    ap.add_argument('--learning_rate', type=float, default=0.03)
    ap.add_argument('--n_estimators', type=int, default=400)
    ap.add_argument('--seed', type=int, default=1234)
    ap.add_argument('--device', default='cuda' if torch.cuda.is_available() else 'cpu')
    args = ap.parse_args()

    if lgb is None:
        raise SystemExit(f'lightgbm import failed. Run: pip install lightgbm\nOriginal error: {_LGBM_IMPORT_ERROR}')

    paired = joblib.load(args.paired_profile)
    if paired.get('profile_type') != 'paired_raw_edited':
        raise SystemExit('Input --paired_profile must be generated by build_paired_profile.py')

    sample_fps = args.sample_fps if args.sample_fps > 0 else float(paired.get('sample_fps', 2.0))
    input_size = args.input_size if args.input_size > 0 else int(paired.get('input_size', 224))
    rng = np.random.default_rng(args.seed)

    print(f'[INFO] device={args.device}')
    print(f'[INFO] paired_profile={args.paired_profile}')
    print(f'[INFO] sample_fps={sample_fps} input_size={input_size}')

    model = load_dinov2_small(args.device)
    tf = build_transform(input_size)

    X_parts, y_parts, group_parts = [], [], []
    source_summaries = []

    for sp in paired.get('source_profiles', []):
        raw_path = Path(sp['raw_path'])
        if not raw_path.exists():
            print(f'[WARN] raw path missing, skip: {raw_path}')
            continue
        if not sp.get('segments'):
            print(f'[WARN] no KEEP segments, skip: {raw_path.name}')
            continue

        print(f'\n[RAW] {raw_path.name}')
        times, embs = extract_video_embeddings(
            str(raw_path), model, tf, args.device,
            sample_fps=sample_fps,
            batch_size=args.batch_size,
            max_frames=args.max_frames_per_video,
            desc=f'lgbm:{raw_path.name[:16]}',
        )
        if embs.shape[0] == 0:
            print(f'[WARN] no embeddings: {raw_path}')
            continue

        y = mask_from_segments(times, sp.get('segments'), label='KEEP').astype(np.int32)
        if int(y.sum()) == 0:
            print(f'[WARN] no positive labels after segment masking: {raw_path.name}')
            continue

        X = make_lgbm_features(embs, times, sample_fps, paired, sp)
        sampled = sample_training_rows(X, y, raw_path.name, args.negative_ratio, rng)
        if sampled is None:
            continue
        Xs, ys, gs = sampled
        X_parts.append(Xs)
        y_parts.append(ys)
        group_parts.append(gs)
        print(f'[INFO] frames={len(y)} pos={int(y.sum())} train_rows={len(ys)} pos_ratio={ys.mean():.3f}')
        source_summaries.append({
            'raw_path': str(raw_path),
            'raw_name': raw_path.name,
            'frames': int(len(y)),
            'positive_frames': int(y.sum()),
            'train_rows': int(len(ys)),
        })

    if not X_parts:
        raise SystemExit('No training rows were created. Check paired segments or lower paired --match_thr first.')

    X_train = np.concatenate(X_parts, axis=0).astype(np.float32)
    y_train = np.concatenate(y_parts, axis=0).astype(np.int32)
    # groups kept for future leave-one-video-out diagnostics.

    pos = int(y_train.sum())
    neg = int(len(y_train) - pos)
    scale_pos_weight = float(neg / max(pos, 1))
    clf = lgb.LGBMClassifier(
        objective='binary',
        n_estimators=args.n_estimators,
        learning_rate=args.learning_rate,
        num_leaves=args.num_leaves,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=1.0,
        min_child_samples=20,
        random_state=args.seed,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
    )
    clf.fit(X_train, y_train)
    pred = clf.predict_proba(X_train)[:, 1]

    profile = {
        'profile_type': 'lightgbm_keep_model',
        'base_profile_type': paired.get('profile_type'),
        'model': 'dinov2_vits14+lightgbm',
        'feature_version': 1,
        'embedding_dim': int(paired.get('embedding_dim', X_train.shape[1])),
        'feature_dim': int(X_train.shape[1]),
        'sample_fps': float(sample_fps),
        'input_size': int(input_size),
        'lgbm_model': clf,
        'base_profile': paired,
        'train_summary': {
            'rows': int(len(y_train)),
            'positive_rows': int(pos),
            'negative_rows': int(neg),
            'positive_ratio': float(y_train.mean()),
            'train_pred_mean': float(pred.mean()),
            'train_pred_pos_mean': float(pred[y_train == 1].mean()) if pos else 0.0,
            'train_pred_neg_mean': float(pred[y_train == 0].mean()) if neg else 0.0,
            'source_count': int(len(source_summaries)),
            'sources': source_summaries,
        },
        'generated_at': datetime.now().isoformat(timespec='seconds'),
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(profile, out)

    meta = dict(profile)
    meta.pop('lgbm_model', None)
    meta['base_profile'] = {
        'profile_type': paired.get('profile_type'),
        'sample_fps': paired.get('sample_fps'),
        'input_size': paired.get('input_size'),
        'source_profiles': len(paired.get('source_profiles', [])),
        'total_positive_embeddings': paired.get('total_positive_embeddings'),
    }
    out.with_suffix('.json').write_text(json.dumps(meta, ensure_ascii=False, indent=2, default=str), encoding='utf-8')
    print(f'\n[DONE] saved LightGBM profile: {out}')
    print(f'[DONE] saved metadata: {out.with_suffix(".json")}')


if __name__ == '__main__':
    main()
